language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements/base.txt --use-mirrors
script:
  - python tests/manage.py test core --settings=settings
